In [1]:
import numpy as np

In [2]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [4]:
rand_array=np.random.randint(0,10,50)
rand_array

array([4, 6, 8, 6, 2, 4, 3, 1, 0, 3, 5, 9, 8, 7, 9, 0, 5, 9, 6, 2, 4, 1,
       6, 2, 1, 1, 4, 6, 4, 8, 5, 2, 2, 0, 9, 6, 3, 3, 8, 9, 5, 2, 9, 5,
       2, 8, 5, 0, 8, 8])

In [5]:
rand_array.max()

9

In [6]:
rand_array.argmax()

11

In [7]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
a=np.random.rand(2,3)
a

array([[0.40478563, 0.8170182 , 0.12069152],
       [0.69419273, 0.51014945, 0.76532792]])

In [11]:
a.T

array([[0.40478563, 0.69419273],
       [0.8170182 , 0.51014945],
       [0.12069152, 0.76532792]])

In [13]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [14]:
sample_array[0]

10

In [15]:
sample_array[2:5]

array([12, 13, 14])

In [16]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [17]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [18]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [19]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [20]:
subset_sample_array[:]=2345
subset_sample_array

array([2345, 2345, 2345, 2345, 2345, 2345, 2345])

In [21]:
import numpy as np

In [22]:
sample_matrix=np.array([[50,20,1,23],[24,23,21,33],[56,76,24,7]])
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [23]:
sample_matrix[1,2]

21

In [24]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [25]:
sample_matrix[2]

array([56, 76, 24,  7])

In [26]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [33, 21],
       [ 7, 24]])

In [27]:
sample_array=np.arange(1,20)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [28]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [29]:
np.exp(sample_array) #exponential

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [30]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [31]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [33]:
np.max(sample_array) #maximum

19

In [34]:
np.min(sample_array) #minimum

1

In [35]:
np.argmax(sample_array)

18

In [36]:
np.argmin(sample_array)

0

In [37]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [38]:
np.std(sample_array)

5.477225575051661

In [39]:
np.var(sample_array)

30.0

In [40]:
np.mean(sample_array)

10.0

In [43]:
array=np.random.randn(3,4)
array

array([[ 0.10154044, -0.49939922, -0.11723811,  0.17564814],
       [ 0.45277495,  0.26591161,  1.31713713, -0.84677299],
       [ 0.50509444,  0.63293204, -1.05634213, -0.85479688]])

In [44]:
np.round(array,decimals=2)

array([[ 0.1 , -0.5 , -0.12,  0.18],
       [ 0.45,  0.27,  1.32, -0.85],
       [ 0.51,  0.63, -1.06, -0.85]])

In [45]:
sports=np.array(["golf","cricket","football","cricket"])
np.unique(sports)

array(['cricket', 'football', 'golf'], dtype='<U8')

### pandas

In [46]:
import pandas as pd
import numpy as np

In [48]:
sports1=pd.Series([1,2,3,4],index=["cricket","football","basketball","golf"])
sports1

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [49]:
sports1["football"]

2

In [50]:
sports2=pd.Series([11,2,3,4],index=["cricket","football","baseball","golf"])
sports2

cricket     11
football     2
baseball     3
golf         4
dtype: int64

In [51]:
sports1+sports2

baseball       NaN
basketball     NaN
cricket       12.0
football       4.0
golf           8.0
dtype: float64

In [53]:
df1=pd.DataFrame(np.random.rand(8,5),index="A B C D E F G H".split(),columns="score1 score2 score3 score4 score5".split())
df1

score1    score2    score3    score4    score5
A  0.813602  0.181344  0.480933  0.723203  0.583702
B  0.303804  0.230553  0.176688  0.856829  0.457129
C  0.602167  0.659714  0.261103  0.953191  0.352368
D  0.656998  0.367404  0.764369  0.921413  0.738848
E  0.439246  0.202860  0.685190  0.337955  0.814613
F  0.950807  0.319538  0.663201  0.798874  0.685629
G  0.136434  0.664914  0.190184  0.835662  0.775510
H  0.390723  0.092421  0.111300  0.938313  0.893935

In [54]:
df1["score1"]

A    0.813602
B    0.303804
C    0.602167
D    0.656998
E    0.439246
F    0.950807
G    0.136434
H    0.390723
Name: score1, dtype: float64

In [59]:
df1[["score1","score2"]]

score1    score2
A  0.813602  0.181344
B  0.303804  0.230553
C  0.602167  0.659714
D  0.656998  0.367404
E  0.439246  0.202860
F  0.950807  0.319538
G  0.136434  0.664914
H  0.390723  0.092421

In [60]:
df1["score6"]=df1["score1"]+df1["score2"]
df1

score1    score2    score3    score4    score5    score6
A  0.813602  0.181344  0.480933  0.723203  0.583702  0.994946
B  0.303804  0.230553  0.176688  0.856829  0.457129  0.534357
C  0.602167  0.659714  0.261103  0.953191  0.352368  1.261882
D  0.656998  0.367404  0.764369  0.921413  0.738848  1.024403
E  0.439246  0.202860  0.685190  0.337955  0.814613  0.642106
F  0.950807  0.319538  0.663201  0.798874  0.685629  1.270346
G  0.136434  0.664914  0.190184  0.835662  0.775510  0.801349
H  0.390723  0.092421  0.111300  0.938313  0.893935  0.483144

In [62]:
df2={"ID":["22","34","56","47"],"name":["joseph","caesar","lelouch","william"],"profit":[35,56,43,71]}
df=pd.DataFrame(df2)
df

ID     name  profit
0  22   joseph      35
1  34   caesar      56
2  56  lelouch      43
3  47  william      71

In [63]:
df["ID"]

0    22
1    34
2    56
3    47
Name: ID, dtype: object

In [64]:
df[["ID","name"]]

ID     name
0  22   joseph
1  34   caesar
2  56  lelouch
3  47  william

In [65]:
df[["ID","name","profit"]]

ID     name  profit
0  22   joseph      35
1  34   caesar      56
2  56  lelouch      43
3  47  william      71

In [66]:
df=df.drop("ID",axis=1)
df

name  profit
0   joseph      35
1   caesar      56
2  lelouch      43
3  william      71

In [67]:
df.drop(3)

name  profit
0   joseph      35
1   caesar      56
2  lelouch      43